### ISSUE TITLE
data.py gives me empty numpy arrays

### ISSUE THREAD

**Issue by adriaromero** [EdwardTyantov/ultrasound-nerve-segmentation#3]
Hi Edward,

Thanks for your code! It's simply amazing! I am trying to run it and adapt it for my own project. 

When I call the function data.py, it creates the .npy files correctly and when I try to open and see those files, I got the following result:

array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ..., 
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]]],

All the .npy are empty and I'd say this is not good :(

Maybe you have a function to convert these numpy array files to image format?

Thanks for your help.

**Comment by EdwardTyantov** [comment]
It requires in ../data/test and /data/train images from the original dataset. When running (data.py) the code iterates file by file in this dirs (function create_train_data), I can't imagine what the problem is. 
If I were you I would simply debug data.py (it's very simple code). Maybe you have some issues with opencv and it converts grayscale or int8 to 0.
