### ISSUE TITLE
Network sturcture

### ISSUE THREAD

**Issue by argman** [EdwardTyantov/ultrasound-nerve-segmentation#9]
Hi Edward, 
    tks for your code, I look at your network structure, find its a mixture of res-like blocks and inception blocks, so I have two questions
1. how do you figure out this structure ? how much better than u-net after the changes ?
2. u-net didnot use padding, but here you use same-padding ? does this matter ?

**Comment by EdwardTyantov** [comment]
Hi, argman.
1. By trial and error ) I gave a talk to my colleagues about this competition. Here is my pres, http://www.slideshare.net/Eduardyantov/ultrasound-segmentation-kaggle-review . I think it answers your questions.
2. I don't think it matters much, because a nerve doesn't appear at the borders.
